name: Run OCI Capacity Script

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: curl, mbstring, openssl

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Write private key to file
        run: |
          echo "${{ secrets.OCI_PRIVATE_KEY }}" > key.pem

      - name: Create .env file
        run: |
          cat << EOF > .env
          OCI_REGION=${{ secrets.OCI_REGION }}
          OCI_USER_ID=${{ secrets.OCI_USER_ID }}
          OCI_TENANCY_ID=${{ secrets.OCI_TENANCY_ID }}
          OCI_KEY_FINGERPRINT=${{ secrets.OCI_KEY_FINGERPRINT }}
          OCI_PRIVATE_KEY_FILENAME=key.pem
          OCI_SUBNET_ID=${{ secrets.OCI_SUBNET_ID }}
          OCI_IMAGE_ID=${{ secrets.OCI_IMAGE_ID }}
          OCI_OCPUS=${{ secrets.OCI_OCPUS }}
          OCI_MEMORY_IN_GBS=${{ secrets.OCI_MEMORY_IN_GBS }}
          OCI_SHAPE=${{ secrets.OCI_SHAPE }}
          OCI_MAX_INSTANCES=${{ secrets.OCI_MAX_INSTANCES }}
          OCI_SSH_PUBLIC_KEY="${{ secrets.OCI_SSH_PUBLIC_KEY }}"
          OCI_AVAILABILITY_DOMAIN=${{ secrets.OCI_AVAILABILITY_DOMAIN }}
          CACHE_AVAILABILITY_DOMAINS=1
          OCI_BOOT_VOLUME_SIZE_IN_GBS=
          OCI_BOOT_VOLUME_ID=
          TOO_MANY_REQUESTS_TIME_WAIT=600
          EOF

      - name: Run script
        run: php index.php
